# This project config file describes your project. See looper docs for details.

metadata:
  sample_annotation: microtest_annotation.tutorial.csv # sheet listing all samples in the project
  output_dir: $HOME/microtest  # ABSOLUTE PATH to the parent, shared space where project results go
  pipeline_interfaces:
    - ${CODE}/open_pipelines/pipeline_interface.yaml  # ABSOLUTE PATH the directory where looper will find the pipeline repository
    - ${CODE}/dnameth_pipelines/pipeline_interface.yaml

data_sources:
  microtest: "microtest/data/{filename}"

genomes:
  human: hg19
  mouse: mm10

transcriptomes:
  human: hg19_cdna
  mouse: mm10_cdna
